// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.Wiki")]
[assembly: AssemblyProductAttribute("Plainion.Notes")]
[assembly: AssemblyDescriptionAttribute("Plainion.Notes")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.Wiki";
        internal const System.String AssemblyProduct = "Plainion.Notes";
        internal const System.String AssemblyDescription = "Plainion.Notes";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "1.0";
        internal const System.String AssemblyFileVersion = "1.0";
    }
}
